### ISSUE TITLE
It's too many bug.

### ISSUE THREAD

**Issue by MikaalSky** [Gigabyte-Giant/gigabyte-giant.github.io#1]
The bug is too many, I swear.
Like, you cannot go to the blog from My Projects
like seriously
come on
We need an exterminatior this is rediculaous.
I'm done.

**Comment by MikaalSky** [comment]
Hire an exterminator already come on.

**Comment by Gigabyte-Giant** [comment]
I added a link to my blog on the "My Projects" page, just a bit ago. See https://github.com/Gigabyte-Giant/gigabyte-giant.github.io/commit/484431d81d6a327ed90730c520dfe95ae4214d3f.

**Comment by Gigabyte-Giant** [comment]
The one "bug" that you reported has been fixed. I'm going to close this now; if you find anymore problems, please create a new issue. Thanks!
